project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!notebooks/working/*.ipynb"
    - "!notebooks/test.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "Handbook on the Indian Ocean Zarr File"
  favicon: images/incois-icon.png
  site-url: https://SAFS-Varanasi-Internship/indian-ocean-zarr
  repo-url: https://github.com/SAFS-Varanasi-Internship/indian-ocean-zarr
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="/images/incois.png" alt="INCOIS logo" style="width:150px"><br />ITCOocean Hack2week (2023)
 
  sidebar:
    logo: images/incois-logos.png
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - text: "About the data set"
        href: index.md
      - section: "Downloading Data"
        contents:
          - text: earthaccess
            href: notebooks/01_earthaccess_Downloader.ipynb
          - text: Copernicus CHL
            href: notebooks/01_Copernicus_Downloader.ipynb
          - text: Copernicus PO
            href: notebooks/01_Copernicus_PO_Downloader.ipynb
          - text: ERA5
            href: notebooks/01_ERA5_GC_Downloader.ipynb
          - text: OPeNDAP
            href: notebooks/01_OPeNDAP_Downloader.ipynb
          - python-notebooks/04_Combining_Data.ipynb
          - python-notebooks/04_Appending_Data.ipynb
      - section: "Processing Data"
        contents:
          - text: CHL
            href: notebooks/02_data_processing_CHL.ipynb
      - text: <img width=100px>
      - text: <img src="/images/ocean-decade.png" width=150px>
        href: https://oceandecade.org/
      - text: DECCaD-IO
        href: https://oceandecade.org/actions/devising-early-career-capacity-development-indocn-deccad-io/
      - text: <img src="/images/ohw.png" width=150px>
        href: https://www.oceanhackweek.org/

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://itcoocean.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/orgs/Hackweek-ITCOocean/discussions
        text: "Discussions"
      - icon: slack
        href: https://app.slack.com/client/T05PV2USY56/C05P7QP47UL
        text: "Slack"
      - icon: globe
        href: https://github.com/Hackweek-ITCOocean
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
