project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!notebooks/working/*.ipynb"
    - "!notebooks/test.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "Handbook on the Indian Ocean Zarr File"
  favicon: images/incois-icon.png
  site-url: https://SAFS-Varanasi-Internship/indian-ocean-zarr
  repo-url: https://github.com/SAFS-Varanasi-Internship/indian-ocean-zarr
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="/images/banner.png" alt="Indian Ocean" style="width:300px">
 
  sidebar:
    title: "Handbook on the Indian Ocean Zarr File"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://safs-varanasi-internship.github.io/indian-ocean-zarr/
        text: "website"
      - icon: github
        href: https://github.com/safs-varanasi-internship/indian-ocean-zarr
        text: "repo"
        
    style: "docked"
    search: true
    collapse-level: 1
    toc-expand: false
    contents:
      - text: "About the data set"
        href: index.md
      - section: "Downloading Data"
        contents:
          - text: earthaccess
            href: notebooks/01_earthaccess_Downloader.ipynb
          - text: Copernicus CHL
            href: notebooks/01_Copernicus_Downloader.ipynb
          - text: Copernicus PO
            href: notebooks/01_Copernicus_PO_Downloader.ipynb
          - text: ERA5
            href: notebooks/01_ERA5_GC_Downloader.ipynb
          - text: OPeNDAP
            href: notebooks/01_OPeNDAP_Downloader.ipynb
          - python-notebooks/04_Combining_Data.ipynb
          - python-notebooks/04_Appending_Data.ipynb
      - section: "Processing Data"
        contents:
          - text: CHL
            href: notebooks/02_data_processing_CHL.ipynb


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
